// Database schema documentation

export interface ColumnDef {
  name: string;
  type: string;
  nullable: boolean;
  default?: string;
  description: string;
}

export interface TableSchema {
  name: string;
  description: string;
  columns: ColumnDef[];
  rlsPolicies: string[];
  relationships: string[];
}

export const DATABASE_SCHEMAS: TableSchema[] = [
  {
    name: 'leads',
    description: 'Stores potential client leads from various sources. Tracks lead status through the sales pipeline from initial contact to conversion. Includes automatic lead scoring.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'lead_number', type: 'text', nullable: false, description: 'Auto-generated lead identifier (LEAD-YYYY-XXXX)' },
      { name: 'first_name', type: 'text', nullable: false, description: 'Lead first name' },
      { name: 'last_name', type: 'text', nullable: false, description: 'Lead last name' },
      { name: 'email', type: 'text', nullable: true, description: 'Contact email address' },
      { name: 'phone', type: 'text', nullable: true, description: 'Contact phone number' },
      { name: 'status', type: 'lead_status', nullable: false, default: 'new', description: 'Current pipeline status: new, contacted, qualified, converted, lost' },
      { name: 'source', type: 'lead_source', nullable: false, default: 'web_form', description: 'Lead acquisition source' },
      { name: 'interest_type', type: 'lead_interest', nullable: false, default: 'debt_resolution', description: 'Type of service interest' },
      { name: 'estimated_debt_amount', type: 'numeric', nullable: true, description: 'Estimated total debt amount' },
      { name: 'assigned_to', type: 'uuid', nullable: true, description: 'Staff member assigned to this lead' },
      { name: 'company_id', type: 'uuid', nullable: false, description: 'Company that owns this lead' },
      { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()', description: 'Record creation timestamp' },
      { name: 'converted_at', type: 'timestamptz', nullable: true, description: 'Timestamp when lead converted to client' },
      { name: 'has_active_lawsuit', type: 'boolean', nullable: true, default: 'false', description: 'Whether lead has active litigation' },
      { name: 'wizard_step', type: 'integer', nullable: true, default: '1', description: 'Current enrollment wizard step' },
      { name: 'wizard_data', type: 'jsonb', nullable: true, default: '{}', description: 'Stored wizard form data' },
      { name: 'lead_score', type: 'integer', nullable: true, default: '0', description: 'Calculated priority score (0-100)' },
      { name: 'score_breakdown', type: 'jsonb', nullable: true, description: 'JSONB breakdown of scoring factors' },
      { name: 'scoring_profile_id', type: 'uuid', nullable: true, description: 'Assigned scoring profile (optional override)' },
      { name: 'score_calculated_at', type: 'timestamptz', nullable: true, description: 'Last score calculation timestamp' },
    ],
    rlsPolicies: [
      'Staff can view company leads - SELECT using can_access_company(auth.uid(), company_id)',
      'Staff can manage company leads - ALL using can_access_company(auth.uid(), company_id)',
    ],
    relationships: [
      'company_id -> companies.id',
      'assigned_to -> staff.id',
      'converted_service_id -> client_services.id',
      'scoring_profile_id -> lead_scoring_profiles.id',
    ],
  },
  {
    name: 'clients',
    description: 'Core client records containing personal information and contact preferences. Linked to services through client_service_clients.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'first_name', type: 'text', nullable: false, description: 'Client first name' },
      { name: 'last_name', type: 'text', nullable: false, description: 'Client last name' },
      { name: 'middle_name', type: 'text', nullable: true, description: 'Client middle name' },
      { name: 'email', type: 'text', nullable: true, description: 'Primary email address' },
      { name: 'date_of_birth', type: 'date', nullable: true, description: 'Date of birth for verification' },
      { name: 'ssn_encrypted', type: 'text', nullable: true, description: 'Encrypted Social Security Number' },
      { name: 'status', type: 'client_status_enum', nullable: true, default: 'inactive', description: 'Active/inactive based on services' },
      { name: 'company_id', type: 'uuid', nullable: false, description: 'Company that manages this client' },
      { name: 'tcpa_consent', type: 'boolean', nullable: true, default: 'false', description: 'TCPA communication consent' },
      { name: 'preferred_contact_method', type: 'phone_type', nullable: true, default: 'mobile', description: 'Preferred contact method' },
      { name: 'is_active', type: 'boolean', nullable: false, default: 'true', description: 'Soft delete flag' },
      { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()', description: 'Record creation timestamp' },
    ],
    rlsPolicies: [
      'Staff can view company clients - SELECT using can_access_company(auth.uid(), company_id)',
      'Staff can manage company clients - ALL using can_access_company(auth.uid(), company_id)',
    ],
    relationships: [
      'company_id -> companies.id',
    ],
  },
  {
    name: 'client_services',
    description: 'Represents an active service engagement (debt settlement program). Links clients to their enrolled services with financial details.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'service_number', type: 'text', nullable: false, description: 'Auto-generated service identifier (SVC-YYYY-XXXX)' },
      { name: 'primary_client_id', type: 'uuid', nullable: true, description: 'Primary client on the service' },
      { name: 'owning_company_id', type: 'uuid', nullable: false, description: 'Company managing this service' },
      { name: 'status', type: 'service_status', nullable: false, default: 'prospect', description: 'Service lifecycle status' },
      { name: 'plan_type', type: 'plan_type', nullable: true, default: 'glg_standard', description: 'Service plan tier' },
      { name: 'total_enrolled_debt', type: 'numeric', nullable: true, default: '0', description: 'Total debt amount enrolled' },
      { name: 'monthly_payment', type: 'numeric', nullable: true, description: 'Monthly escrow payment amount' },
      { name: 'escrow_balance', type: 'numeric', nullable: true, default: '0', description: 'Current escrow account balance' },
      { name: 'settlement_fee_percentage', type: 'numeric', nullable: true, default: '25', description: 'Fee percentage on settlements' },
      { name: 'term_months', type: 'integer', nullable: true, description: 'Program duration in months' },
      { name: 'enrolled_date', type: 'date', nullable: true, description: 'Service enrollment date' },
      { name: 'first_payment_date', type: 'date', nullable: true, description: 'First scheduled payment date' },
      { name: 'contact_status', type: 'contact_status_enum', nullable: true, default: 'reachable', description: 'Client reachability status' },
      { name: 'payment_status', type: 'payment_status_enum', nullable: true, description: 'Payment health status' },
      { name: 'retention_flag', type: 'boolean', nullable: true, default: 'false', description: 'Flagged for retention team' },
      { name: 'retention_type', type: 'retention_type_enum', nullable: true, description: 'Type of retention issue' },
    ],
    rlsPolicies: [
      'Staff can view company client_services - SELECT using can_access_company(auth.uid(), owning_company_id)',
      'Staff can manage company client_services - ALL using can_access_company(auth.uid(), owning_company_id)',
    ],
    relationships: [
      'owning_company_id -> companies.id',
      'primary_client_id -> clients.id',
      'originating_company_id -> companies.id',
    ],
  },
  {
    name: 'liabilities',
    description: 'Individual debt accounts enrolled in a client service. Tracks creditor information and balance changes through the settlement process.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'client_service_id', type: 'uuid', nullable: false, description: 'Parent service record' },
      { name: 'original_creditor_id', type: 'uuid', nullable: true, description: 'Original creditor reference' },
      { name: 'current_creditor_id', type: 'uuid', nullable: true, description: 'Current creditor (may differ from original)' },
      { name: 'debt_buyer_id', type: 'uuid', nullable: true, description: 'Debt buyer if account was sold' },
      { name: 'law_firm_id', type: 'uuid', nullable: true, description: 'Collection law firm if applicable' },
      { name: 'liability_type', type: 'liability_type', nullable: false, default: 'credit_card', description: 'Type of debt account' },
      { name: 'account_number', type: 'text', nullable: true, description: 'Account number (masked)' },
      { name: 'original_balance', type: 'numeric', nullable: true, description: 'Balance when account opened' },
      { name: 'enrolled_balance', type: 'numeric', nullable: true, description: 'Balance when enrolled in program' },
      { name: 'current_balance', type: 'numeric', nullable: true, description: 'Current balance with interest/fees' },
      { name: 'status', type: 'liability_status', nullable: false, default: 'enrolled', description: 'Settlement pipeline status' },
      { name: 'priority', type: 'integer', nullable: true, default: '0', description: 'Settlement priority order' },
    ],
    rlsPolicies: [
      'Staff can access liabilities - ALL using EXISTS (SELECT 1 FROM client_services cs WHERE cs.id = client_service_id AND can_access_company(auth.uid(), cs.owning_company_id))',
    ],
    relationships: [
      'client_service_id -> client_services.id',
      'original_creditor_id -> creditors.id',
      'current_creditor_id -> creditors.id',
      'debt_buyer_id -> creditors.id',
      'law_firm_id -> creditors.id',
    ],
  },
  {
    name: 'settlements',
    description: 'Settlement offers and negotiations for liabilities. Tracks offer amounts, payment schedules, and attorney approvals.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'liability_id', type: 'uuid', nullable: false, description: 'Liability being settled' },
      { name: 'offer_amount', type: 'numeric', nullable: false, description: 'Settlement offer amount' },
      { name: 'offer_percentage', type: 'numeric', nullable: true, description: 'Settlement as percentage of balance' },
      { name: 'status', type: 'settlement_status', nullable: false, default: 'offered', description: 'Offer status: offered, accepted, rejected, completed' },
      { name: 'payment_type', type: 'payment_type', nullable: false, default: 'lump_sum', description: 'Lump sum or payment plan' },
      { name: 'number_of_payments', type: 'integer', nullable: true, default: '1', description: 'Number of settlement payments' },
      { name: 'first_payment_date', type: 'date', nullable: true, description: 'First settlement payment date' },
      { name: 'payment_schedule', type: 'jsonb', nullable: true, default: '[]', description: 'Payment schedule details' },
      { name: 'offered_date', type: 'date', nullable: false, default: 'CURRENT_DATE', description: 'Date offer was made' },
      { name: 'accepted_date', type: 'date', nullable: true, description: 'Date offer was accepted' },
      { name: 'completed_date', type: 'date', nullable: true, description: 'Date settlement was completed' },
      { name: 'attorney_approved', type: 'boolean', nullable: true, default: 'false', description: 'Attorney approval status' },
      { name: 'attorney_approved_by', type: 'uuid', nullable: true, description: 'Approving attorney' },
      { name: 'fee_collection_method', type: 'fee_collection_method', nullable: true, default: 'split', description: 'How fees are collected' },
    ],
    rlsPolicies: [
      'Staff can access settlements - ALL using EXISTS (SELECT 1 FROM liabilities l JOIN client_services cs ON cs.id = l.client_service_id WHERE l.id = liability_id AND can_access_company(auth.uid(), cs.owning_company_id))',
    ],
    relationships: [
      'liability_id -> liabilities.id',
      'attorney_approved_by -> staff.id',
    ],
  },
  {
    name: 'litigation_matters',
    description: 'Legal cases arising from debt collection. Tracks court information, deadlines, and case outcomes.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'liability_id', type: 'uuid', nullable: false, description: 'Related liability' },
      { name: 'client_service_id', type: 'uuid', nullable: false, description: 'Parent service' },
      { name: 'case_number', type: 'text', nullable: true, description: 'Court case number' },
      { name: 'court_name', type: 'text', nullable: true, description: 'Court name' },
      { name: 'state', type: 'text', nullable: true, description: 'State where filed' },
      { name: 'county', type: 'text', nullable: true, description: 'County where filed' },
      { name: 'status', type: 'litigation_status', nullable: false, default: 'new', description: 'Case status' },
      { name: 'opposing_party', type: 'text', nullable: true, description: 'Plaintiff/creditor name' },
      { name: 'opposing_counsel', type: 'text', nullable: true, description: 'Opposing attorney' },
      { name: 'service_date', type: 'date', nullable: true, description: 'Date served with lawsuit' },
      { name: 'response_deadline', type: 'date', nullable: true, description: 'Answer/response deadline' },
      { name: 'next_hearing_date', type: 'timestamptz', nullable: true, description: 'Next scheduled hearing' },
      { name: 'judgment_amount', type: 'numeric', nullable: true, description: 'Judgment amount if entered' },
      { name: 'settlement_amount', type: 'numeric', nullable: true, description: 'Settlement amount if resolved' },
    ],
    rlsPolicies: [
      'Staff can access litigation matters - ALL using EXISTS (SELECT 1 FROM client_services cs WHERE cs.id = client_service_id AND can_access_company(auth.uid(), cs.owning_company_id))',
    ],
    relationships: [
      'liability_id -> liabilities.id',
      'client_service_id -> client_services.id',
    ],
  },
  {
    name: 'transactions',
    description: 'All financial transactions including escrow deposits, settlement payments, and fee collections.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'client_service_id', type: 'uuid', nullable: false, description: 'Related service' },
      { name: 'liability_id', type: 'uuid', nullable: true, description: 'Related liability if applicable' },
      { name: 'settlement_id', type: 'uuid', nullable: true, description: 'Related settlement if applicable' },
      { name: 'transaction_type', type: 'text', nullable: false, description: 'Type: escrow_deposit, settlement_payment, contingency_fee, service_fee' },
      { name: 'amount', type: 'numeric', nullable: false, description: 'Transaction amount' },
      { name: 'status', type: 'text', nullable: false, default: 'pending', description: 'pending, processed, failed, cancelled' },
      { name: 'scheduled_date', type: 'date', nullable: true, description: 'Scheduled processing date' },
      { name: 'processed_at', type: 'timestamptz', nullable: true, description: 'Actual processing timestamp' },
      { name: 'processor_id', type: 'uuid', nullable: true, description: 'Payment processor used' },
      { name: 'external_id', type: 'text', nullable: true, description: 'External processor reference' },
      { name: 'error_message', type: 'text', nullable: true, description: 'Error details if failed' },
      { name: 'parent_transaction_id', type: 'uuid', nullable: true, description: 'Parent for split payments' },
      { name: 'sequence_number', type: 'integer', nullable: true, description: 'Payment sequence in series' },
    ],
    rlsPolicies: [
      'Staff can access transactions - ALL using EXISTS (SELECT 1 FROM client_services cs WHERE cs.id = client_service_id AND can_access_company(auth.uid(), cs.owning_company_id))',
    ],
    relationships: [
      'client_service_id -> client_services.id',
      'liability_id -> liabilities.id',
      'settlement_id -> settlements.id',
      'processor_id -> payment_processors.id',
      'parent_transaction_id -> transactions.id',
    ],
  },
  {
    name: 'tasks',
    description: 'Task management for staff workflow. Supports linking to any entity type for context.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'title', type: 'text', nullable: false, description: 'Task title' },
      { name: 'description', type: 'text', nullable: true, description: 'Detailed description' },
      { name: 'task_type', type: 'task_type', nullable: false, default: 'general', description: 'Task category' },
      { name: 'status', type: 'task_status', nullable: false, default: 'pending', description: 'pending, in_progress, completed, cancelled' },
      { name: 'priority', type: 'task_priority', nullable: false, default: 'medium', description: 'low, medium, high, urgent' },
      { name: 'due_date', type: 'timestamptz', nullable: true, description: 'Task due date' },
      { name: 'assigned_to', type: 'uuid', nullable: true, description: 'Assigned staff member' },
      { name: 'created_by', type: 'uuid', nullable: true, description: 'Staff who created task' },
      { name: 'company_id', type: 'uuid', nullable: false, description: 'Company ownership' },
      { name: 'entity_type', type: 'entity_type', nullable: true, description: 'Type of linked entity' },
      { name: 'entity_id', type: 'uuid', nullable: true, description: 'ID of linked entity' },
      { name: 'completed_at', type: 'timestamptz', nullable: true, description: 'Completion timestamp' },
    ],
    rlsPolicies: [
      'Staff can view company tasks - SELECT using can_access_company(auth.uid(), company_id)',
      'Staff can manage company tasks - ALL using can_access_company(auth.uid(), company_id)',
    ],
    relationships: [
      'company_id -> companies.id',
      'assigned_to -> staff.id',
      'created_by -> staff.id',
    ],
  },
  {
    name: 'staff',
    description: 'Staff member profiles linked to auth users. Contains department and role information.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'user_id', type: 'uuid', nullable: false, description: 'Auth user reference' },
      { name: 'company_id', type: 'uuid', nullable: false, description: 'Company employment' },
      { name: 'first_name', type: 'text', nullable: false, description: 'Staff first name' },
      { name: 'last_name', type: 'text', nullable: false, description: 'Staff last name' },
      { name: 'email', type: 'text', nullable: false, description: 'Work email' },
      { name: 'phone', type: 'text', nullable: true, description: 'Work phone' },
      { name: 'department', type: 'department_enum', nullable: false, description: 'Department assignment' },
      { name: 'job_title', type: 'text', nullable: true, description: 'Job title' },
      { name: 'avatar_url', type: 'text', nullable: true, description: 'Profile avatar URL' },
      { name: 'is_active', type: 'boolean', nullable: false, default: 'true', description: 'Active employment status' },
    ],
    rlsPolicies: [
      'Staff can view accessible staff - SELECT using can_access_company(auth.uid(), company_id)',
      'Staff can update own profile - UPDATE using user_id = auth.uid()',
    ],
    relationships: [
      'company_id -> companies.id',
      'user_id -> auth.users.id',
    ],
  },
  {
    name: 'companies',
    description: 'Company/organization records. Supports parent-child relationships for franchise structures.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'name', type: 'text', nullable: false, description: 'Company name' },
      { name: 'company_type', type: 'company_type', nullable: false, default: 'law_firm', description: 'Organization type' },
      { name: 'parent_company_id', type: 'uuid', nullable: true, description: 'Parent company for subsidiaries' },
      { name: 'data_visibility', type: 'data_visibility', nullable: false, default: 'own_only', description: 'Data sharing level' },
      { name: 'address_line1', type: 'text', nullable: true, description: 'Street address' },
      { name: 'city', type: 'text', nullable: true, description: 'City' },
      { name: 'state', type: 'text', nullable: true, description: 'State' },
      { name: 'zip_code', type: 'text', nullable: true, description: 'ZIP code' },
      { name: 'phone', type: 'text', nullable: true, description: 'Main phone' },
      { name: 'email', type: 'text', nullable: true, description: 'Main email' },
      { name: 'website', type: 'text', nullable: true, description: 'Company website' },
      { name: 'settings', type: 'jsonb', nullable: true, default: '{}', description: 'Company-specific settings' },
      { name: 'is_active', type: 'boolean', nullable: false, default: 'true', description: 'Active status' },
    ],
    rlsPolicies: [
      'Staff can view accessible companies - SELECT using can_access_company(auth.uid(), id)',
      'Admins can manage companies - ALL using has_role(auth.uid(), \'admin\')',
    ],
    relationships: [
      'parent_company_id -> companies.id',
    ],
  },
  {
    name: 'creditors',
    description: 'Master list of creditors, debt buyers, and collection law firms for reference across liabilities.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'name', type: 'text', nullable: false, description: 'Creditor name' },
      { name: 'creditor_type', type: 'creditor_type', nullable: false, default: 'original_creditor', description: 'original_creditor, debt_buyer, collection_agency, law_firm' },
      { name: 'phone', type: 'text', nullable: true, description: 'Contact phone' },
      { name: 'fax', type: 'text', nullable: true, description: 'Fax number' },
      { name: 'email', type: 'text', nullable: true, description: 'Contact email' },
      { name: 'address_line1', type: 'text', nullable: true, description: 'Street address' },
      { name: 'city', type: 'text', nullable: true, description: 'City' },
      { name: 'state', type: 'text', nullable: true, description: 'State' },
      { name: 'zip_code', type: 'text', nullable: true, description: 'ZIP code' },
      { name: 'notes', type: 'text', nullable: true, description: 'Internal notes' },
      { name: 'is_active', type: 'boolean', nullable: false, default: 'true', description: 'Active in system' },
    ],
    rlsPolicies: [
      'All staff can view creditors - SELECT using true',
      'Admins can manage creditors - ALL using has_role(auth.uid(), \'admin\')',
    ],
    relationships: [],
  },
  {
    name: 'report_templates',
    description: 'Saved report configurations for quick re-run. Includes system presets and user-created templates.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'company_id', type: 'uuid', nullable: true, description: 'Company ownership (null for presets)' },
      { name: 'created_by', type: 'uuid', nullable: true, description: 'Creating staff member' },
      { name: 'name', type: 'text', nullable: false, description: 'Template name' },
      { name: 'description', type: 'text', nullable: true, description: 'Template description' },
      { name: 'module', type: 'text', nullable: false, description: 'Source data module' },
      { name: 'config', type: 'jsonb', nullable: false, default: '{}', description: 'Report configuration: columns, filters, chart settings' },
      { name: 'is_preset', type: 'boolean', nullable: false, default: 'false', description: 'System preset flag' },
      { name: 'is_public', type: 'boolean', nullable: false, default: 'false', description: 'Shared with company' },
    ],
    rlsPolicies: [
      'Staff can access company report templates - ALL using (company_id IS NULL AND is_preset = true) OR can_access_company(auth.uid(), company_id)',
    ],
    relationships: [
      'company_id -> companies.id',
      'created_by -> staff.id',
    ],
  },
  {
    name: 'notifications',
    description: 'User notifications for system events. Supports real-time updates via Supabase Realtime.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'user_id', type: 'uuid', nullable: false, description: 'Target user for notification' },
      { name: 'type', type: 'notification_type', nullable: false, description: 'Notification category: task_assigned, lead_assigned, etc.' },
      { name: 'title', type: 'text', nullable: false, description: 'Notification headline' },
      { name: 'message', type: 'text', nullable: true, description: 'Detailed notification message' },
      { name: 'link', type: 'text', nullable: true, description: 'Navigation path (e.g., /tasks/abc123)' },
      { name: 'entity_type', type: 'text', nullable: true, description: 'Related entity type: task, lead, matter' },
      { name: 'entity_id', type: 'uuid', nullable: true, description: 'Related entity ID' },
      { name: 'is_read', type: 'boolean', nullable: false, default: 'false', description: 'Read status' },
      { name: 'read_at', type: 'timestamptz', nullable: true, description: 'Timestamp when marked read' },
      { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()', description: 'Creation timestamp' },
    ],
    rlsPolicies: [
      'Users can view own notifications - SELECT using user_id = auth.uid()',
      'Users can update own notifications - UPDATE using user_id = auth.uid()',
      'System can insert notifications - INSERT using true (via triggers)',
    ],
    relationships: [
      'user_id -> auth.users.id',
    ],
  },
  {
    name: 'notification_preferences',
    description: 'User preferences for notification delivery channels per notification type.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'user_id', type: 'uuid', nullable: false, description: 'User these preferences apply to' },
      { name: 'notification_type', type: 'notification_type', nullable: false, description: 'Notification type this preference controls' },
      { name: 'in_app_enabled', type: 'boolean', nullable: false, default: 'true', description: 'Show in-app notifications' },
      { name: 'email_enabled', type: 'boolean', nullable: false, default: 'false', description: 'Send email notifications' },
      { name: 'sound_enabled', type: 'boolean', nullable: false, default: 'true', description: 'Play notification sound' },
      { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()', description: 'Creation timestamp' },
      { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()', description: 'Last update timestamp' },
    ],
    rlsPolicies: [
      'Users can manage own preferences - ALL using user_id = auth.uid()',
    ],
    relationships: [
      'user_id -> auth.users.id',
    ],
  },
  {
    name: 'lead_scoring_profiles',
    description: 'Configurable scoring profiles for lead prioritization. Criteria stored as JSONB for flexibility.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'company_id', type: 'uuid', nullable: false, description: 'Company that owns this profile' },
      { name: 'name', type: 'text', nullable: false, description: 'Profile name' },
      { name: 'description', type: 'text', nullable: true, description: 'Profile description' },
      { name: 'interest_type', type: 'lead_interest', nullable: true, description: 'Only apply to specific interest type' },
      { name: 'source', type: 'lead_source', nullable: true, description: 'Only apply to specific lead source' },
      { name: 'is_default', type: 'boolean', nullable: false, default: 'false', description: 'Default profile for company' },
      { name: 'is_active', type: 'boolean', nullable: false, default: 'true', description: 'Profile is active' },
      { name: 'criteria', type: 'jsonb', nullable: false, default: '{}', description: 'Scoring criteria: debt thresholds, source weights, etc.' },
      { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()', description: 'Creation timestamp' },
      { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()', description: 'Last update timestamp' },
    ],
    rlsPolicies: [
      'Users can view company scoring profiles - SELECT using company_id = get_user_company_id(auth.uid())',
      'Users can manage company scoring profiles - ALL using company_id = get_user_company_id(auth.uid())',
    ],
    relationships: [
      'company_id -> companies.id',
    ],
  },
  {
    name: 'lead_assignment_rules',
    description: 'Configurable rules for automatic lead distribution. Supports multiple assignment methods and filtering criteria.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'company_id', type: 'uuid', nullable: false, description: 'Company that owns this rule' },
      { name: 'name', type: 'text', nullable: false, description: 'Rule name' },
      { name: 'description', type: 'text', nullable: true, description: 'Rule description' },
      { name: 'method', type: 'assignment_method', nullable: false, default: 'round_robin', description: 'Distribution method: round_robin, weighted, load_balanced, skillset_match' },
      { name: 'source', type: 'lead_source', nullable: true, description: 'Only apply to specific lead source' },
      { name: 'interest_type', type: 'lead_interest', nullable: true, description: 'Only apply to specific interest type' },
      { name: 'min_debt_amount', type: 'numeric', nullable: true, description: 'Minimum debt threshold' },
      { name: 'max_debt_amount', type: 'numeric', nullable: true, description: 'Maximum debt threshold' },
      { name: 'priority', type: 'integer', nullable: false, default: '0', description: 'Rule priority (higher runs first)' },
      { name: 'is_default', type: 'boolean', nullable: false, default: 'false', description: 'Default rule for company' },
      { name: 'is_active', type: 'boolean', nullable: false, default: 'true', description: 'Rule is active' },
      { name: 'config', type: 'jsonb', nullable: false, default: '{}', description: 'Additional configuration options' },
    ],
    rlsPolicies: [
      'Users can view company assignment rules - SELECT using company_id = get_user_company_id(auth.uid())',
      'Users can manage company assignment rules - ALL using company_id = get_user_company_id(auth.uid())',
    ],
    relationships: [
      'company_id -> companies.id',
    ],
  },
  {
    name: 'lead_assignment_pool',
    description: 'Staff members available for lead assignment under specific rules. Tracks capacity and availability.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'rule_id', type: 'uuid', nullable: false, description: 'Parent assignment rule' },
      { name: 'staff_id', type: 'uuid', nullable: false, description: 'Staff member in pool' },
      { name: 'weight', type: 'integer', nullable: false, default: '1', description: 'Weight for weighted distribution' },
      { name: 'max_active_leads', type: 'integer', nullable: true, description: 'Maximum concurrent leads (null = unlimited)' },
      { name: 'is_available', type: 'boolean', nullable: false, default: 'true', description: 'Currently available for assignments' },
      { name: 'skills', type: 'jsonb', nullable: true, description: 'Skills for skillset matching' },
      { name: 'assignment_count', type: 'integer', nullable: false, default: '0', description: 'Total assignments received' },
      { name: 'last_assigned_at', type: 'timestamptz', nullable: true, description: 'Last assignment timestamp' },
    ],
    rlsPolicies: [
      'Users can access assignment pool - ALL using EXISTS (SELECT 1 FROM lead_assignment_rules r WHERE r.id = rule_id AND r.company_id = get_user_company_id(auth.uid()))',
    ],
    relationships: [
      'rule_id -> lead_assignment_rules.id',
      'staff_id -> staff.id',
    ],
  },
  {
    name: 'lead_assignment_queue',
    description: 'Queue for leads awaiting assignment when no pool members are available.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'lead_id', type: 'uuid', nullable: false, description: 'Lead awaiting assignment' },
      { name: 'rule_id', type: 'uuid', nullable: true, description: 'Matched assignment rule' },
      { name: 'priority', type: 'integer', nullable: false, default: '0', description: 'Queue priority' },
      { name: 'status', type: 'queue_status', nullable: false, default: 'pending', description: 'Queue item status' },
      { name: 'queued_at', type: 'timestamptz', nullable: false, default: 'now()', description: 'When added to queue' },
      { name: 'assigned_at', type: 'timestamptz', nullable: true, description: 'When assigned' },
      { name: 'assigned_to', type: 'uuid', nullable: true, description: 'Assigned staff member' },
      { name: 'attempt_count', type: 'integer', nullable: false, default: '0', description: 'Assignment attempts' },
    ],
    rlsPolicies: [
      'Users can view assignment queue - SELECT using EXISTS (SELECT 1 FROM leads l WHERE l.id = lead_id AND l.company_id = get_user_company_id(auth.uid()))',
    ],
    relationships: [
      'lead_id -> leads.id',
      'rule_id -> lead_assignment_rules.id',
      'assigned_to -> staff.id',
    ],
  },
  {
    name: 'lead_assignment_log',
    description: 'Audit log of all lead assignment actions for tracking and analytics.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'lead_id', type: 'uuid', nullable: false, description: 'Lead that was assigned' },
      { name: 'action', type: 'assignment_action', nullable: false, description: 'Action type: assigned, reassigned, unassigned' },
      { name: 'from_staff_id', type: 'uuid', nullable: true, description: 'Previous assignee (for reassignment)' },
      { name: 'to_staff_id', type: 'uuid', nullable: true, description: 'New assignee' },
      { name: 'method', type: 'assignment_method', nullable: true, description: 'Assignment method used' },
      { name: 'rule_id', type: 'uuid', nullable: true, description: 'Rule that triggered assignment' },
      { name: 'reason', type: 'text', nullable: true, description: 'Reason for assignment/reassignment' },
      { name: 'performed_by', type: 'uuid', nullable: true, description: 'Staff who performed action' },
      { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()', description: 'Action timestamp' },
    ],
    rlsPolicies: [
      'Users can view assignment log - SELECT using EXISTS (SELECT 1 FROM leads l WHERE l.id = lead_id AND l.company_id = get_user_company_id(auth.uid()))',
    ],
    relationships: [
      'lead_id -> leads.id',
      'from_staff_id -> staff.id',
      'to_staff_id -> staff.id',
      'rule_id -> lead_assignment_rules.id',
      'performed_by -> staff.id',
    ],
  },
  {
    name: 'workflow_rules',
    description: 'Configurable workflow automation rules with triggers, conditions, and actions. Supports blocking rules for status transitions.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'company_id', type: 'uuid', nullable: false, description: 'Company that owns this rule' },
      { name: 'name', type: 'text', nullable: false, description: 'Workflow rule name' },
      { name: 'description', type: 'text', nullable: true, description: 'Rule description' },
      { name: 'entity_type', type: 'workflow_entity_type', nullable: false, description: 'Entity this rule applies to' },
      { name: 'trigger_type', type: 'workflow_trigger_type', nullable: false, description: 'Event that triggers the rule' },
      { name: 'trigger_config', type: 'jsonb', nullable: false, default: '{}', description: 'Trigger configuration (from/to statuses, field name, etc.)' },
      { name: 'conditions', type: 'jsonb', nullable: false, default: '[]', description: 'Condition groups with AND/OR logic' },
      { name: 'actions', type: 'jsonb', nullable: false, default: '[]', description: 'Actions to execute when conditions pass' },
      { name: 'is_active', type: 'boolean', nullable: false, default: 'true', description: 'Rule is active' },
      { name: 'is_blocking', type: 'boolean', nullable: false, default: 'false', description: 'Rule can block status transitions' },
      { name: 'priority', type: 'integer', nullable: false, default: '0', description: 'Execution priority (higher runs first)' },
      { name: 'created_by', type: 'uuid', nullable: true, description: 'Staff who created the rule' },
    ],
    rlsPolicies: [
      'Users can view company workflow rules - SELECT using company_id = get_user_company_id(auth.uid())',
      'Users can manage company workflow rules - ALL using company_id = get_user_company_id(auth.uid())',
    ],
    relationships: [
      'company_id -> companies.id',
      'created_by -> staff.id',
    ],
  },
  {
    name: 'workflow_executions',
    description: 'Audit log of workflow rule executions. Tracks trigger data, condition results, and action outcomes.',
    columns: [
      { name: 'id', type: 'uuid', nullable: false, default: 'gen_random_uuid()', description: 'Primary key' },
      { name: 'rule_id', type: 'uuid', nullable: false, description: 'Workflow rule that executed' },
      { name: 'entity_type', type: 'workflow_entity_type', nullable: false, description: 'Entity type that triggered execution' },
      { name: 'entity_id', type: 'uuid', nullable: false, description: 'Entity that triggered execution' },
      { name: 'status', type: 'workflow_execution_status', nullable: false, description: 'Execution result: success, blocked, failed, skipped' },
      { name: 'trigger_data', type: 'jsonb', nullable: true, description: 'Data that triggered the workflow' },
      { name: 'condition_results', type: 'jsonb', nullable: true, description: 'Which conditions passed/failed' },
      { name: 'actions_executed', type: 'jsonb', nullable: true, description: 'Results of executed actions' },
      { name: 'error_message', type: 'text', nullable: true, description: 'Error message if failed' },
      { name: 'block_message', type: 'text', nullable: true, description: 'User-facing message if blocked' },
      { name: 'duration_ms', type: 'integer', nullable: true, description: 'Execution time in milliseconds' },
      { name: 'executed_at', type: 'timestamptz', nullable: false, default: 'now()', description: 'Execution timestamp' },
    ],
    rlsPolicies: [
      'Staff can view workflow executions - SELECT using EXISTS (SELECT 1 FROM workflow_rules r WHERE r.id = rule_id AND r.company_id = get_user_company_id(auth.uid()))',
    ],
    relationships: [
      'rule_id -> workflow_rules.id',
    ],
  },
];

export const ENUM_DEFINITIONS = [
  {
    name: 'lead_status',
    values: ['new', 'contacted', 'qualified', 'converted', 'lost'],
    description: 'Lead pipeline stages',
  },
  {
    name: 'lead_source',
    values: ['web_form', 'phone', 'referral', 'marketing', 'partner'],
    description: 'Lead acquisition channels',
  },
  {
    name: 'service_status',
    values: ['prospect', 'pending_docs', 'pending_payment', 'active', 'paused', 'graduated', 'cancelled', 'terminated'],
    description: 'Service lifecycle stages',
  },
  {
    name: 'liability_status',
    values: ['enrolled', 'negotiating', 'offer_pending', 'settled', 'paid_off', 'litigation', 'removed'],
    description: 'Liability settlement pipeline',
  },
  {
    name: 'settlement_status',
    values: ['offered', 'counter_offered', 'accepted', 'rejected', 'in_progress', 'completed', 'defaulted'],
    description: 'Settlement offer states',
  },
  {
    name: 'litigation_status',
    values: ['new', 'served', 'answer_filed', 'discovery', 'mediation', 'trial', 'judgment', 'settled', 'dismissed', 'closed'],
    description: 'Litigation case stages',
  },
  {
    name: 'task_status',
    values: ['pending', 'in_progress', 'completed', 'cancelled'],
    description: 'Task completion states',
  },
  {
    name: 'task_priority',
    values: ['low', 'medium', 'high', 'urgent'],
    description: 'Task priority levels',
  },
  {
    name: 'app_role',
    values: ['admin', 'attorney', 'case_manager', 'negotiator', 'sales_rep', 'client_services_rep', 'payment_processor', 'correspondence'],
    description: 'Application user roles',
  },
  {
    name: 'department_enum',
    values: ['admin', 'sales', 'client_services', 'legal', 'case_management', 'negotiations', 'payment_processing', 'correspondence'],
    description: 'Staff department assignments',
  },
  {
    name: 'creditor_type',
    values: ['original_creditor', 'debt_buyer', 'collection_agency', 'law_firm'],
    description: 'Types of creditor entities',
  },
  {
    name: 'liability_type',
    values: ['credit_card', 'personal_loan', 'medical', 'auto_deficiency', 'private_student_loan', 'business_debt', 'other'],
    description: 'Types of debt accounts',
  },
  {
    name: 'notification_type',
    values: ['task_assigned', 'task_due_soon', 'task_overdue', 'lead_assigned', 'matter_assigned', 'hearing_reminder', 'settlement_update', 'mention', 'system_alert'],
    description: 'Types of system notifications',
  },
  {
    name: 'assignment_method',
    values: ['round_robin', 'weighted', 'load_balanced', 'skillset_match'],
    description: 'Methods for distributing leads to staff',
  },
  {
    name: 'assignment_action',
    values: ['assigned', 'reassigned', 'unassigned'],
    description: 'Types of assignment log actions',
  },
  {
    name: 'queue_status',
    values: ['pending', 'processing', 'assigned', 'failed', 'expired'],
    description: 'Assignment queue item states',
  },
  {
    name: 'workflow_trigger_type',
    values: ['status_changed', 'field_updated', 'record_created', 'time_based', 'manual'],
    description: 'Events that can trigger workflow rules',
  },
  {
    name: 'workflow_entity_type',
    values: ['leads', 'client_services', 'liabilities', 'litigation_matters', 'tasks', 'settlements'],
    description: 'Entities that workflow rules can apply to',
  },
  {
    name: 'workflow_action_type',
    values: ['create_task', 'send_notification', 'update_field', 'block_transition', 'trigger_webhook'],
    description: 'Actions that workflows can execute',
  },
  {
    name: 'workflow_execution_status',
    values: ['success', 'blocked', 'failed', 'skipped'],
    description: 'Outcomes of workflow rule execution',
  },
];

export const DATABASE_FUNCTIONS = [
  {
    name: 'can_access_company',
    signature: 'can_access_company(_user_id uuid, _company_id uuid) RETURNS boolean',
    description: 'Checks if a user has access to a company based on their staff record. Used in RLS policies for multi-tenant data isolation.',
    securityDefiner: true,
  },
  {
    name: 'has_role',
    signature: 'has_role(_user_id uuid, _role app_role) RETURNS boolean',
    description: 'Checks if a user has a specific role assigned. Used for role-based access control in RLS policies.',
    securityDefiner: true,
  },
  {
    name: 'get_user_company_id',
    signature: 'get_user_company_id(_user_id uuid) RETURNS uuid',
    description: 'Returns the company ID for a given user based on their staff record.',
    securityDefiner: true,
  },
  {
    name: 'generate_lead_number',
    signature: 'generate_lead_number() RETURNS trigger',
    description: 'Trigger function that auto-generates lead numbers in format LEAD-YYYY-XXXX.',
    securityDefiner: false,
  },
  {
    name: 'generate_service_number',
    signature: 'generate_service_number() RETURNS trigger',
    description: 'Trigger function that auto-generates service numbers in format SVC-YYYY-XXXX.',
    securityDefiner: false,
  },
  {
    name: 'update_client_status',
    signature: 'update_client_status() RETURNS trigger',
    description: 'Trigger function that updates client status based on their active services.',
    securityDefiner: true,
  },
  {
    name: 'track_lead_status_transition',
    signature: 'track_lead_status_transition() RETURNS trigger',
    description: 'Trigger function that records timestamps when lead status changes.',
    securityDefiner: false,
  },
  {
    name: 'create_notification',
    signature: 'create_notification(_user_id uuid, _type notification_type, _title text, _message text, _link text, _entity_type text, _entity_id uuid) RETURNS uuid',
    description: 'Creates a notification for a user, respecting their notification preferences. Returns the notification ID.',
    securityDefiner: true,
  },
  {
    name: 'notify_task_assignment',
    signature: 'notify_task_assignment() RETURNS trigger',
    description: 'Trigger function that creates a notification when a task is assigned or reassigned to a staff member.',
    securityDefiner: true,
  },
  {
    name: 'calculate_lead_score',
    signature: 'calculate_lead_score(lead_row leads) RETURNS TABLE(score integer, breakdown jsonb)',
    description: 'Calculates lead score based on assigned or default scoring profile. Returns score and breakdown of contributing factors.',
    securityDefiner: true,
  },
  {
    name: 'trigger_calculate_lead_score',
    signature: 'trigger_calculate_lead_score() RETURNS trigger',
    description: 'Trigger function that auto-calculates lead score on insert or update of scoring-relevant fields.',
    securityDefiner: true,
  },
  {
    name: 'assign_lead',
    signature: 'assign_lead(_lead_id uuid, _rule_id uuid) RETURNS TABLE(assigned_to uuid, assignment_method text, reason text)',
    description: 'Assigns a lead to a staff member based on assignment rule configuration. Supports round_robin, weighted, load_balanced, and skillset_match methods.',
    securityDefiner: true,
  },
  {
    name: 'process_assignment_queue',
    signature: 'process_assignment_queue() RETURNS TABLE(lead_id uuid, assigned_to uuid, status text)',
    description: 'Processes pending leads in the assignment queue. Called periodically to assign queued leads.',
    securityDefiner: true,
  },
  {
    name: 'validate_status_transition',
    signature: 'validate_status_transition(_entity_type workflow_entity_type, _entity_id uuid, _from_status text, _to_status text) RETURNS TABLE(allowed boolean, block_message text, rule_name text)',
    description: 'Validates whether a status transition is allowed based on workflow rules. Returns blocking message if transition is prevented.',
    securityDefiner: true,
  },
  {
    name: 'evaluate_workflow_conditions',
    signature: 'evaluate_workflow_conditions(_conditions jsonb, _entity_type workflow_entity_type, _entity_id uuid) RETURNS boolean',
    description: 'Evaluates workflow conditions against an entity. Supports field comparisons and related entity checks.',
    securityDefiner: true,
  },
];

export const EDGE_FUNCTIONS = [
  {
    name: 'create-staff-user',
    path: 'supabase/functions/create-staff-user',
    description: 'Creates a new staff user with auth credentials and staff profile. Called during staff onboarding.',
    authentication: 'Service role (no JWT verification)',
    inputs: [
      { name: 'email', type: 'string', description: 'User email address' },
      { name: 'password', type: 'string', description: 'Initial password' },
      { name: 'first_name', type: 'string', description: 'Staff first name' },
      { name: 'last_name', type: 'string', description: 'Staff last name' },
      { name: 'company_id', type: 'string', description: 'Company UUID' },
      { name: 'department', type: 'string', description: 'Department enum value' },
      { name: 'role', type: 'string', description: 'App role to assign' },
    ],
    outputs: 'Created user and staff record',
  },
  {
    name: 'process-deadline-reminders',
    path: 'supabase/functions/process-deadline-reminders',
    description: 'Processes pending deadline reminders and creates notifications. Runs hourly via pg_cron.',
    authentication: 'Service role (scheduled execution)',
    inputs: [],
    outputs: 'JSON with processed count, sent, failed stats',
  },
  {
    name: 'render-template',
    path: 'supabase/functions/render-template',
    description: 'Renders a template with merge fields replaced by entity data. Supports lead, client, service, liability, and litigation entities.',
    authentication: 'JWT required (authenticated users)',
    inputs: [
      { name: 'template_id', type: 'string', description: 'Template UUID to render' },
      { name: 'entity_type', type: 'string', description: 'Type of entity: lead, client, client_service, liability, litigation_matter' },
      { name: 'entity_id', type: 'string', description: 'Entity UUID to pull data from' },
    ],
    outputs: 'Rendered template content with merge fields replaced',
  },
  {
    name: 'docuseal-send',
    path: 'supabase/functions/docuseal-send',
    description: 'Creates a DocuSeal submission for signature requests. Handles template selection, signer configuration, and submission creation via DocuSeal API.',
    authentication: 'JWT required (authenticated users)',
    inputs: [
      { name: 'signature_request_id', type: 'string', description: 'CRM signature request UUID' },
    ],
    outputs: 'JSON with submission_id, signing URLs, and status',
  },
  {
    name: 'docuseal-webhook',
    path: 'supabase/functions/docuseal-webhook',
    description: 'Receives DocuSeal webhook events (form.viewed, form.started, form.completed, form.declined, submission.completed). Updates signature request status and retrieves executed documents.',
    authentication: 'None (public webhook endpoint)',
    inputs: [
      { name: 'event_type', type: 'string', description: 'DocuSeal event type' },
      { name: 'data', type: 'object', description: 'Event payload with submission details' },
    ],
    outputs: 'Acknowledgment response',
  },
  {
    name: 'docuseal-test',
    path: 'supabase/functions/docuseal-test',
    description: 'Tests DocuSeal API connectivity and lists available templates. Used to verify API key configuration.',
    authentication: 'None (diagnostic endpoint)',
    inputs: [],
    outputs: 'JSON with connection status and template list',
  },
  {
    name: 'reset-staff-password',
    path: 'supabase/functions/reset-staff-password',
    description: 'Resets a staff user password. Admin function for password recovery.',
    authentication: 'Service role (admin only)',
    inputs: [
      { name: 'user_id', type: 'string', description: 'Auth user UUID' },
      { name: 'new_password', type: 'string', description: 'New password to set' },
    ],
    outputs: 'Success confirmation',
  },
  {
    name: 'simulate-underwriting',
    path: 'supabase/functions/simulate-underwriting',
    description: 'Runs the simulated underwriting engine for an eligibility review. Calculates affordability, debt ratios, and program fit then writes results back to the review record.',
    authentication: 'JWT required (authenticated users)',
    inputs: [
      { name: 'eligibility_review_id', type: 'string', description: 'Eligibility review UUID to evaluate' },
    ],
    outputs: 'JSON with score, flags, recommended term, and decision payload',
  },
  {
    name: 'forth-auth',
    path: 'supabase/functions/forth-auth',
    description: 'Authenticates with the Forth CRM OAuth endpoint and caches the access token (~9 day TTL). Shared helper used by all other forth-* functions.',
    authentication: 'None (diagnostic endpoint); requires FORTH_CLIENT_ID and FORTH_API_KEY secrets',
    inputs: [],
    outputs: 'JSON with success flag and tokenPreview',
  },
  {
    name: 'forth-create-draft',
    path: 'supabase/functions/forth-create-draft',
    description: 'Creates a payment draft in Forth Pay from a CRM transaction. Stores the returned Forth draft_id on the transaction record.',
    authentication: 'Service role',
    inputs: [
      { name: 'transaction_id', type: 'string', description: 'CRM transaction UUID to push to Forth' },
    ],
    outputs: 'JSON with success flag and forth draft_id',
  },
  {
    name: 'forth-cancel-draft',
    path: 'supabase/functions/forth-cancel-draft',
    description: 'Cancels an existing Forth Pay draft. Respects the 7-day lock window enforced upstream.',
    authentication: 'Service role',
    inputs: [
      { name: 'transaction_id', type: 'string', description: 'CRM transaction UUID linked to the Forth draft' },
    ],
    outputs: 'JSON with success flag and message',
  },
  {
    name: 'forth-update-draft',
    path: 'supabase/functions/forth-update-draft',
    description: 'Updates a Forth Pay draft (process date and/or amount). Blocked when the draft is inside the 7-day lock window.',
    authentication: 'Service role',
    inputs: [
      { name: 'transaction_id', type: 'string', description: 'CRM transaction UUID' },
      { name: 'process_date', type: 'string?', description: 'New process date (ISO)' },
      { name: 'amount', type: 'number?', description: 'New draft amount' },
    ],
    outputs: 'JSON with success flag and updated draft fields',
  },
  {
    name: 'forth-poll-transactions',
    path: 'supabase/functions/forth-poll-transactions',
    description: 'Polls Forth Pay for the status of all pending transactions and reconciles open/pending/cleared/cancelled state into the CRM ledger.',
    authentication: 'Service role (scheduled)',
    inputs: [],
    outputs: 'JSON with polled, updated, and errors counts',
  },
  {
    name: 'forth-sync-client',
    path: 'supabase/functions/forth-sync-client',
    description: 'Syncs a CRM client with Forth CRM. Supports fetch, link (by forth_crm_id), and post_note actions. Persists forth_crm_id on the client.',
    authentication: 'Service role',
    inputs: [
      { name: 'client_id', type: 'string', description: 'CRM client UUID' },
      { name: 'forth_crm_id', type: 'string?', description: 'Existing Forth contact id when linking' },
      { name: 'action', type: 'string?', description: 'fetch | link | post_note' },
      { name: 'note', type: 'string?', description: 'Note body when action=post_note' },
    ],
    outputs: 'JSON with success flag, forth_crm_id, and contact payload',
  },
  {
    name: 'forth-pause-resume',
    path: 'supabase/functions/forth-pause-resume',
    description: 'Pauses or resumes all drafts for a client in Forth Pay. Used when a service goes on hold or returns to active.',
    authentication: 'Service role',
    inputs: [
      { name: 'client_id', type: 'string', description: 'CRM client UUID' },
      { name: 'action', type: 'string', description: 'pause | resume' },
    ],
    outputs: 'JSON with success flag and message',
  },
  {
    name: 'forth-register-client',
    path: 'supabase/functions/forth-register-client',
    description: 'Registers a new client in Forth Pay during enrollment: creates the contact, bank account, debts, and enrolls the program in one call. Runs in the background from the Enrollment Wizard.',
    authentication: 'Service role',
    inputs: [
      { name: 'client_id', type: 'string', description: 'CRM client UUID' },
      { name: 'client_service_id', type: 'string', description: 'CRM client_service UUID' },
      { name: 'client_data', type: 'object', description: 'Demographics, address, contact, DOB, SSN' },
      { name: 'banking', type: 'object?', description: 'Routing/account/bank metadata' },
      { name: 'debts', type: 'array', description: 'List of debts with creditor, balance, account info' },
    ],
    outputs: 'JSON with success flag, forth_crm_id, and optional warning',
  },
];

export const STORAGE_BUCKETS = [
  {
    name: 'litigation-documents',
    isPublic: true,
    description: 'Stores litigation-related documents: court filings, summons, answers, motions.',
    policies: [
      'Authenticated users can upload to their company folder',
      'Staff can view documents for their company cases',
    ],
  },
  {
    name: 'client-documents',
    isPublic: true,
    description: 'Stores client documents: IDs, contracts, disclosures, correspondence.',
    policies: [
      'Authenticated users can upload to their company folder',
      'Staff can view documents for their company clients',
    ],
  },
  {
    name: 'signed-documents',
    isPublic: false,
    description: 'Stores executed signature documents from DocuSeal. Contains signed PDFs and completion certificates.',
    policies: [
      'Staff can view signed documents for their company',
      'System can upload via service role (webhook)',
    ],
  },
  {
    name: 'lead-documents',
    isPublic: false,
    description: 'Stores lead intake documents: budgets, IDs, statements uploaded during the lead/eligibility phase.',
    policies: [
      'Authenticated staff can upload to their company folder',
      'Staff can view documents for leads in their company',
    ],
  },
];
