import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import type { Tables, TablesInsert, TablesUpdate, Enums } from '@/integrations/supabase/types';

export type ClientService = Tables<'client_services'> & {
  primary_client?: Tables<'clients'> | null;
  client_service_clients?: (Tables<'client_service_clients'> & {
    client?: Tables<'clients'>;
  })[];
  client_service_types?: (Tables<'client_service_types'> & {
    service?: Tables<'services'>;
  })[];
};

export type ClientServiceInsert = Omit<TablesInsert<'client_services'>, 'id' | 'created_at' | 'updated_at' | 'service_number'>;
export type ClientServiceUpdate = TablesUpdate<'client_services'>;
export type ServiceStatus = Enums<'service_status'>;
export type ClientRelationship = Enums<'client_relationship'>;

export function useClientServices(status?: ServiceStatus) {
  return useQuery({
    queryKey: ['client_services', status],
    queryFn: async () => {
      let query = supabase
        .from('client_services')
        .select(`
          *,
          primary_client:clients!client_services_primary_client_id_fkey(id, first_name, last_name, email),
          client_service_types(
            *,
            service:services(id, name, service_type)
          )
        `)
        .order('created_at', { ascending: false });

      if (status) {
        query = query.eq('status', status);
      }

      const { data, error } = await query;
      if (error) throw error;
      // Transform primary_client from array to single object (Supabase returns array for FK joins)
      return (data || []).map(item => ({
        ...item,
        primary_client: Array.isArray(item.primary_client) ? item.primary_client[0] : item.primary_client,
      })) as ClientService[];
    },
  });
}

export function useClientService(id: string | undefined) {
  return useQuery({
    queryKey: ['client_service', id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from('client_services')
        .select(`
          *,
          primary_client:clients!client_services_primary_client_id_fkey(id, first_name, last_name, email),
          client_service_clients(
            *,
            client:clients(id, first_name, last_name, email)
          ),
          client_service_types(
            *,
            service:services(id, name, service_type)
          )
        `)
        .eq('id', id)
        .single();
      if (error) throw error;
      // Transform primary_client from array to single object
      return {
        ...data,
        primary_client: Array.isArray(data.primary_client) ? data.primary_client[0] : data.primary_client,
      } as ClientService;
    },
    enabled: !!id,
  });
}

export function useCreateClientService() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (clientService: ClientServiceInsert) => {
      // service_number is auto-generated by trigger
      const { data, error } = await supabase
        .from('client_services')
        .insert([{ ...clientService, service_number: '' }] as any)
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['client_services'] });
      toast({ title: 'Service created successfully' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to create service', description: error.message, variant: 'destructive' });
    },
  });
}

export function useUpdateClientService() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, ...updates }: ClientServiceUpdate & { id: string }) => {
      const { data, error } = await supabase
        .from('client_services')
        .update(updates)
        .eq('id', id)
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['client_services'] });
      queryClient.invalidateQueries({ queryKey: ['client_service', data.id] });
      toast({ title: 'Service updated successfully' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to update service', description: error.message, variant: 'destructive' });
    },
  });
}

export function useUpdateClientServiceStatus() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, status }: { id: string; status: ServiceStatus }) => {
      const updates: any = { status };
      if (status === 'active') {
        updates.enrolled_date = new Date().toISOString();
        updates.program_start_date = new Date().toISOString().split('T')[0];
      } else if (status === 'closed') {
        updates.closed_date = new Date().toISOString();
      }
      
      const { data, error } = await supabase
        .from('client_services')
        .update(updates)
        .eq('id', id)
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['client_services'] });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to update status', description: error.message, variant: 'destructive' });
    },
  });
}

// Client service clients (junction table)
export function useAddClientServiceClient() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: TablesInsert<'client_service_clients'>) => {
      const { data: result, error } = await supabase
        .from('client_service_clients')
        .insert([data])
        .select()
        .single();
      if (error) throw error;
      return result;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['client_service', data.client_service_id] });
      toast({ title: 'Client added to service' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to add client', description: error.message, variant: 'destructive' });
    },
  });
}

export function useRemoveClientServiceClient() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, clientServiceId }: { id: string; clientServiceId: string }) => {
      const { error } = await supabase
        .from('client_service_clients')
        .delete()
        .eq('id', id);
      if (error) throw error;
      return clientServiceId;
    },
    onSuccess: (clientServiceId) => {
      queryClient.invalidateQueries({ queryKey: ['client_service', clientServiceId] });
      toast({ title: 'Client removed from service' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to remove client', description: error.message, variant: 'destructive' });
    },
  });
}

// Client service types (services offered)
export function useAddClientServiceType() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: TablesInsert<'client_service_types'>) => {
      const { data: result, error } = await supabase
        .from('client_service_types')
        .insert([data])
        .select()
        .single();
      if (error) throw error;
      return result;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['client_service', data.client_service_id] });
      toast({ title: 'Service type added' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to add service type', description: error.message, variant: 'destructive' });
    },
  });
}

export function useRemoveClientServiceType() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, clientServiceId }: { id: string; clientServiceId: string }) => {
      const { error } = await supabase
        .from('client_service_types')
        .delete()
        .eq('id', id);
      if (error) throw error;
      return clientServiceId;
    },
    onSuccess: (clientServiceId) => {
      queryClient.invalidateQueries({ queryKey: ['client_service', clientServiceId] });
      toast({ title: 'Service type removed' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to remove service type', description: error.message, variant: 'destructive' });
    },
  });
}
