import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import type { Tables, TablesInsert, TablesUpdate, Enums } from '@/integrations/supabase/types';

export type Engagement = Tables<'engagements'> & {
  primary_contact?: Tables<'contacts'> | null;
  engagement_contacts?: (Tables<'engagement_contacts'> & {
    contact?: Tables<'contacts'>;
  })[];
  engagement_services?: (Tables<'engagement_services'> & {
    service?: Tables<'services'>;
  })[];
};

export type EngagementInsert = Omit<TablesInsert<'engagements'>, 'id' | 'created_at' | 'updated_at' | 'engagement_number'>;
export type EngagementUpdate = TablesUpdate<'engagements'>;
export type EngagementStatus = Enums<'engagement_status'>;
export type ContactRelationship = Enums<'contact_relationship'>;

export function useEngagements(status?: EngagementStatus) {
  return useQuery({
    queryKey: ['engagements', status],
    queryFn: async () => {
      let query = supabase
        .from('engagements')
        .select(`
          *,
          primary_contact:contacts!engagements_primary_contact_id_fkey(id, first_name, last_name, email),
          engagement_services(
            *,
            service:services(id, name, service_type)
          )
        `)
        .order('created_at', { ascending: false });

      if (status) {
        query = query.eq('status', status);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as Engagement[];
    },
  });
}

export function useEngagement(id: string | undefined) {
  return useQuery({
    queryKey: ['engagement', id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from('engagements')
        .select(`
          *,
          primary_contact:contacts!engagements_primary_contact_id_fkey(id, first_name, last_name, email),
          engagement_contacts(
            *,
            contact:contacts(id, first_name, last_name, email)
          ),
          engagement_services(
            *,
            service:services(id, name, service_type)
          )
        `)
        .eq('id', id)
        .single();
      if (error) throw error;
      return data as Engagement;
    },
    enabled: !!id,
  });
}

export function useCreateEngagement() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (engagement: EngagementInsert) => {
      // engagement_number is auto-generated by trigger
      const { data, error } = await supabase
        .from('engagements')
        .insert([{ ...engagement, engagement_number: '' }] as any)
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['engagements'] });
      toast({ title: 'Engagement created successfully' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to create engagement', description: error.message, variant: 'destructive' });
    },
  });
}

export function useUpdateEngagement() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, ...updates }: EngagementUpdate & { id: string }) => {
      const { data, error } = await supabase
        .from('engagements')
        .update(updates)
        .eq('id', id)
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['engagements'] });
      queryClient.invalidateQueries({ queryKey: ['engagement', data.id] });
      toast({ title: 'Engagement updated successfully' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to update engagement', description: error.message, variant: 'destructive' });
    },
  });
}

export function useUpdateEngagementStatus() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, status }: { id: string; status: EngagementStatus }) => {
      const updates: any = { status };
      if (status === 'active') {
        updates.enrolled_date = new Date().toISOString();
      } else if (status === 'closed') {
        updates.closed_date = new Date().toISOString();
      }
      
      const { data, error } = await supabase
        .from('engagements')
        .update(updates)
        .eq('id', id)
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['engagements'] });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to update status', description: error.message, variant: 'destructive' });
    },
  });
}

// Engagement contacts
export function useAddEngagementContact() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: TablesInsert<'engagement_contacts'>) => {
      const { data: result, error } = await supabase
        .from('engagement_contacts')
        .insert([data])
        .select()
        .single();
      if (error) throw error;
      return result;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['engagement', data.engagement_id] });
      toast({ title: 'Contact added to engagement' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to add contact', description: error.message, variant: 'destructive' });
    },
  });
}

export function useRemoveEngagementContact() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, engagementId }: { id: string; engagementId: string }) => {
      const { error } = await supabase
        .from('engagement_contacts')
        .delete()
        .eq('id', id);
      if (error) throw error;
      return engagementId;
    },
    onSuccess: (engagementId) => {
      queryClient.invalidateQueries({ queryKey: ['engagement', engagementId] });
      toast({ title: 'Contact removed from engagement' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to remove contact', description: error.message, variant: 'destructive' });
    },
  });
}

// Engagement services
export function useAddEngagementService() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: TablesInsert<'engagement_services'>) => {
      const { data: result, error } = await supabase
        .from('engagement_services')
        .insert([data])
        .select()
        .single();
      if (error) throw error;
      return result;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['engagement', data.engagement_id] });
      toast({ title: 'Service added to engagement' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to add service', description: error.message, variant: 'destructive' });
    },
  });
}

export function useRemoveEngagementService() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, engagementId }: { id: string; engagementId: string }) => {
      const { error } = await supabase
        .from('engagement_services')
        .delete()
        .eq('id', id);
      if (error) throw error;
      return engagementId;
    },
    onSuccess: (engagementId) => {
      queryClient.invalidateQueries({ queryKey: ['engagement', engagementId] });
      toast({ title: 'Service removed from engagement' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to remove service', description: error.message, variant: 'destructive' });
    },
  });
}
