import { useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import type { Tables } from '@/integrations/supabase/types';
import type { LitigationData } from '@/components/litigation/LitigationWizard';

type Lead = Tables<'leads'>;

interface ConversionResult {
  clientId: string;
  clientServiceId: string;
  liabilityId: string;
  matterId: string;
}

interface ConversionInput {
  lead: Lead;
  data: LitigationData;
  companyId: string;
}

export function useLitigationConversion() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ lead, data, companyId }: ConversionInput): Promise<ConversionResult> => {
      // Step 1: Create client from lead data
      const { data: client, error: clientError } = await supabase
        .from('clients')
        .insert({
          first_name: lead.first_name,
          last_name: lead.last_name,
          email: lead.email,
          company_id: companyId,
          date_of_birth: lead.date_of_birth,
          notes: `Converted from lead ${lead.lead_number} (litigation interest)`,
        })
        .select()
        .single();
      
      if (clientError) throw new Error(`Failed to create client: ${clientError.message}`);

      // Step 2: Create client_service record
      const { data: clientService, error: serviceError } = await supabase
        .from('client_services')
        .insert({
          owning_company_id: companyId,
          primary_client_id: client.id,
          status: 'pending',
          program_type: 'litigation',
          total_enrolled_debt: data.debt_amount || 0,
          notes: `Litigation case - ${data.case_type === 'debt_defense' ? 'Debt Defense' : 'Other'}`,
          service_number: '', // Will be auto-generated by trigger
        } as any)
        .select()
        .single();
      
      if (serviceError) throw new Error(`Failed to create service: ${serviceError.message}`);

      // Step 3: Create liability record
      const { data: liability, error: liabilityError } = await supabase
        .from('liabilities')
        .insert({
          client_service_id: clientService.id,
          status: 'in_litigation',
          liability_type: 'credit_card', // Default type
          enrolled_balance: data.debt_amount || 0,
          current_balance: data.debt_amount || 0,
          notes: `Opposing party: ${data.opposing_party || 'Unknown'}`,
        })
        .select()
        .single();
      
      if (liabilityError) throw new Error(`Failed to create liability: ${liabilityError.message}`);

      // Step 4: Create litigation_matter record
      const { data: matter, error: matterError } = await supabase
        .from('litigation_matters')
        .insert({
          client_service_id: clientService.id,
          liability_id: liability.id,
          status: 'new',
          state: data.state,
          case_number: data.case_number || null,
          court_name: data.court_name || null,
          opposing_party: data.opposing_party || null,
          service_date: data.service_date || null,
          response_deadline: data.response_deadline || null,
        })
        .select()
        .single();
      
      if (matterError) throw new Error(`Failed to create litigation matter: ${matterError.message}`);

      // Step 5: Update lead with converted status and reference
      const { error: leadError } = await supabase
        .from('leads')
        .update({
          status: 'converted',
          converted_service_id: clientService.id,
          converted_at: new Date().toISOString(),
        })
        .eq('id', lead.id);
      
      if (leadError) throw new Error(`Failed to update lead: ${leadError.message}`);

      // Step 6: Create client phone if lead has phone
      if (lead.phone) {
        await supabase
          .from('client_phones')
          .insert({
            client_id: client.id,
            phone_number: lead.phone,
            phone_type: 'mobile',
            is_primary: true,
          });
      }

      return {
        clientId: client.id,
        clientServiceId: clientService.id,
        liabilityId: liability.id,
        matterId: matter.id,
      };
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['leads'] });
      queryClient.invalidateQueries({ queryKey: ['clients'] });
      queryClient.invalidateQueries({ queryKey: ['client_services'] });
      queryClient.invalidateQueries({ queryKey: ['liabilities'] });
      queryClient.invalidateQueries({ queryKey: ['litigation_matters'] });
      toast({ title: 'Lead converted to litigation case successfully!' });
    },
    onError: (error: Error) => {
      toast({ 
        title: 'Conversion failed', 
        description: error.message, 
        variant: 'destructive' 
      });
    },
  });
}
