import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import type { Tables, TablesInsert, TablesUpdate, Enums, Json } from '@/integrations/supabase/types';
import type { ScoreBreakdown } from '@/types/scoring';

export type Lead = Tables<'leads'> & {
  assigned_staff?: Tables<'staff'> | null;
  // Typed score breakdown
  score_breakdown_typed?: ScoreBreakdown | null;
};

export type LeadInsert = Omit<TablesInsert<'leads'>, 'lead_number' | 'id' | 'created_at' | 'updated_at'>;
export type LeadUpdate = TablesUpdate<'leads'>;
export type LeadStatus = Enums<'lead_status'>;

export interface UseLeadsOptions {
  status?: LeadStatus;
  page?: number;
  pageSize?: number;
}

export interface PaginatedLeadsResult {
  data: Lead[];
  count: number;
}

// Helper to parse score breakdown from JSON
function parseScoreBreakdown(breakdown: Json | null): ScoreBreakdown | null {
  if (!breakdown || typeof breakdown !== 'object' || Array.isArray(breakdown)) {
    return null;
  }
  return breakdown as unknown as ScoreBreakdown;
}

export function useLeads(options: UseLeadsOptions = {}) {
  const { status, page, pageSize } = options;
  const isPaginated = page !== undefined && pageSize !== undefined;
  
  return useQuery({
    queryKey: ['leads', { status, page, pageSize }],
    queryFn: async (): Promise<PaginatedLeadsResult> => {
      let query = supabase
        .from('leads')
        .select(`
          *,
          assigned_staff:staff!leads_assigned_to_fkey(id, first_name, last_name, avatar_url)
        `, { count: 'exact' })
        .order('lead_score', { ascending: false, nullsFirst: false })
        .order('created_at', { ascending: false });

      if (status) {
        query = query.eq('status', status);
      }

      // Apply pagination only if page and pageSize are provided
      if (isPaginated) {
        const from = (page - 1) * pageSize;
        const to = from + pageSize - 1;
        query = query.range(from, to);
      }

      const { data, error, count } = await query;
      if (error) throw error;
      
      // Add typed score breakdown to each lead
      const leadsWithTypedBreakdown = (data || []).map(lead => ({
        ...lead,
        score_breakdown_typed: parseScoreBreakdown(lead.score_breakdown),
      })) as Lead[];
      
      return { data: leadsWithTypedBreakdown, count: count ?? 0 };
    },
  });
}

export function useLead(id: string | undefined) {
  return useQuery({
    queryKey: ['lead', id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from('leads')
        .select(`
          *,
          assigned_staff:staff!leads_assigned_to_fkey(id, first_name, last_name, avatar_url, email)
        `)
        .eq('id', id)
        .single();
      if (error) throw error;
      return {
        ...data,
        score_breakdown_typed: parseScoreBreakdown(data.score_breakdown),
      } as Lead;
    },
    enabled: !!id,
  });
}

export function useCreateLead() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (lead: LeadInsert) => {
      // lead_number is auto-generated by trigger
      const { data, error } = await supabase
        .from('leads')
        .insert([{ ...lead, lead_number: '' }] as any)
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['leads'] });
      toast({ title: 'Lead created successfully' });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to create lead', description: error.message, variant: 'destructive' });
    },
  });
}

export function useUpdateLead() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, ...updates }: LeadUpdate & { id: string }) => {
      const { data, error } = await supabase
        .from('leads')
        .update(updates)
        .eq('id', id)
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['leads'] });
      queryClient.invalidateQueries({ queryKey: ['lead', data.id] });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to update lead', description: error.message, variant: 'destructive' });
    },
  });
}

export function useUpdateLeadStatus() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, status }: { id: string; status: LeadStatus }) => {
      const { data, error } = await supabase
        .from('leads')
        .update({ status })
        .eq('id', id)
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['leads'] });
    },
    onError: (error: Error) => {
      toast({ title: 'Failed to update status', description: error.message, variant: 'destructive' });
    },
  });
}
