create or replace view DATA_ALPS.DATA_VAULT.VW_MASS_SETTLEMENT_OFFER_CALCULATIONS(
	OFFER_ID,
	DEBT_ID,
	CONTACT_ID,
	FIRST_PAYMENT_DATE,
	MIN_RUNNING_BALANCE,
	OFFER_VERDICT,
	ADDITIONAL_FUNDS_NEEDED,
	MIN_BALANCE_REMAINING,
	URL_TO_OFFER
) as 
WITH
CTE_TRANSACTIONS AS (
    SELECT 
        *
    FROM DATA_ALPS.DATA_VAULT.VW_TRANSACTIONS_2
    WHERE 
        TRANSACTIONS_STATUS_NAME IN ('Open', 'Pending', 'Cleared', 'Shipped', 'Low Balance')
    AND NOT (TRANSACTIONS_STATUS_NAME = 'Open' AND PROCESS_DATE < CURRENT_DATE())
),

CTE_SETTLEMENT_OFFERS_TO_CALCULATE AS (
    SELECT 
        *
    FROM DATA_ALPS.DATA_VAULT.VW_SETTLEMENT_OFFER_PARSED_PAYMENTS
    WHERE SETTLEMENT_OFFER_STATUS_NAME IN ('Funds Calculation')
),

CTE_SETTLEMENT_FEES_TO_CALCULATE AS (
    SELECT 
        *
    FROM DATA_ALPS.DATA_VAULT.VW_SETTLEMENT_OFFER_PARSED_FEES
    WHERE SETTLEMENT_OFFER_STATUS_NAME IN ('Funds Calculation')
),

-- Earliest date across both payments and fees per offer
CTE_OFFER_START AS (
    SELECT
        OFFER_ID,
        MIN(PROCESS_DATE) AS FIRST_PAYMENT_DATE
    FROM (
        SELECT OFFER_ID, PROCESS_DATE FROM CTE_SETTLEMENT_OFFERS_TO_CALCULATE
        UNION ALL
        SELECT OFFER_ID, PROCESS_DATE FROM CTE_SETTLEMENT_FEES_TO_CALCULATE
    )
    GROUP BY OFFER_ID
),

-- Unify existing transactions + offer payments + offer fees into one timeline per offer
CTE_COMBINED AS (
    -- Existing transactions
    SELECT
        COTC.OFFER_ID,
        COTC.DEBT_ID,
        CT.CONTACT_ID,
        CT.PROCESS_DATE,
        CT.NET_AMOUNT,
        CT.TRANSACTION_TYPE_NAME AS SOURCE_TYPE,
        CT.TRANSACTIONS_STATUS_NAME AS STATUS_NAME,
        'EXISTING_TRANSACTION' AS RECORD_SOURCE,
        CT.ID AS SORT_KEY
    FROM CTE_TRANSACTIONS CT
    INNER JOIN (
        SELECT DISTINCT 
            OFFER_ID, DEBT_ID, 
            CONTACT_ID
        FROM CTE_SETTLEMENT_OFFERS_TO_CALCULATE
    ) COTC
        ON CT.CONTACT_ID = COTC.CONTACT_ID

    UNION ALL

    -- Settlement payments as outflows
    SELECT
        OFFER_ID,
        DEBT_ID,
        CONTACT_ID,
        PROCESS_DATE,
        (-1 * AMOUNT) - 6 AS NET_AMOUNT,
        PAYMENT_TYPE_NAME AS SOURCE_TYPE,
        'Open' AS STATUS_NAME,
        'SETTLEMENT_PAYMENT' AS RECORD_SOURCE,
        PAYMENT_NUM AS SORT_KEY
    FROM CTE_SETTLEMENT_OFFERS_TO_CALCULATE

    UNION ALL

    -- Settlement fees as outflows
    SELECT
        OFFER_ID,
        DEBT_ID,
        CONTACT_ID,
        PROCESS_DATE,
        -1 * AMOUNT AS NET_AMOUNT,
        'SETTLEMENT_FEE' AS SOURCE_TYPE,
        'Open' AS STATUS_NAME,
        'SETTLEMENT_FEE' AS RECORD_SOURCE,
        PAYMENT_NUM AS SORT_KEY
    FROM CTE_SETTLEMENT_FEES_TO_CALCULATE
),

-- Running balance per offer simulation
CTE_RUNNING_BALANCE AS (
    SELECT
        CC.OFFER_ID,
        CC.DEBT_ID,
        CC.CONTACT_ID,
        CC.PROCESS_DATE,
        CC.NET_AMOUNT,
        CC.SOURCE_TYPE,
        CC.STATUS_NAME,
        CC.RECORD_SOURCE,
        CC.SORT_KEY,
        COS1.FIRST_PAYMENT_DATE,
        SUM(CC.NET_AMOUNT) OVER (PARTITION BY CC.OFFER_ID, CC.CONTACT_ID ORDER BY CC.PROCESS_DATE, CC.RECORD_SOURCE, CC.SORT_KEY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUNNING_BALANCE
    FROM CTE_COMBINED CC
    INNER JOIN CTE_OFFER_START COS1
        ON CC.OFFER_ID = COS1.OFFER_ID
)

SELECT
    OFFER_ID,
    DEBT_ID,
    CONTACT_ID,
    FIRST_PAYMENT_DATE,
    
    -- PROCESS_DATE,
    -- NET_AMOUNT,
    -- STATUS_NAME,
    -- SOURCE_TYPE,
    -- RECORD_SOURCE,
    
    MIN(RUNNING_BALANCE) AS MIN_RUNNING_BALANCE,
    IFF(MIN(RUNNING_BALANCE) < 0, 'CLIENT GOES SHORT', 'OK') AS OFFER_VERDICT,
    IFF(MIN(RUNNING_BALANCE) < 0, ABS(MIN(RUNNING_BALANCE)), NULL) AS ADDITIONAL_FUNDS_NEEDED,
    IFF(MIN(RUNNING_BALANCE) >= 0, MIN(RUNNING_BALANCE), NULL) AS MIN_BALANCE_REMAINING,
    CONCAT('https://client.forthcrm.com/index.php?module=settlements&page=new4&sid=', OFFER_ID) AS URL_TO_OFFER
    
FROM 
    CTE_RUNNING_BALANCE
WHERE 
    PROCESS_DATE >= FIRST_PAYMENT_DATE
GROUP BY 
    OFFER_ID, 
    DEBT_ID, 
    CONTACT_ID, 
    FIRST_PAYMENT_DATE
ORDER BY 
    OFFER_ID;