create or replace view DATA_ALPS.DATA_VAULT.VW_SETTLEMENT_OFFER_PARSED_FEES(
	DEBT_ID,
	OFFER_ID,
	CONTACT_ID,
	PROCESS_DATE,
	PAYMENT_TYPE_NAME,
	AMOUNT,
	SETTLEMENT_OFFER_STATUS_NAME,
	PAYMENT_NUM,
	SYNC_TIMESTAMP
) as
SELECT
    DEBT_ID,
    SETTLEMENT_OFFERS.ID AS OFFER_ID,
    CONTACT_ID,
    TRY_TO_DATE(FLATTENED_FEES.value:process_date::STRING, 'MM/DD/YYYY') AS PROCESS_DATE,
    'Earned Performance Fee' AS PAYMENT_TYPE_NAME,
    TRY_TO_DOUBLE(FLATTENED_FEES.value:amount::STRING) AS AMOUNT,
    IFNULL(SETTLEMENT_OFFER_STATUS_NAME1, 'Completed') AS SETTLEMENT_OFFER_STATUS_NAME,
    ROW_NUMBER() OVER (PARTITION BY SETTLEMENT_OFFERS.ID ORDER BY PROCESS_DATE ASC) AS PAYMENT_NUM,
    CURRENT_TIMESTAMP() AS SYNC_TIMESTAMP

FROM DPP_DATA.READER.SETTLEMENT_OFFERS AS SETTLEMENT_OFFERS
LEFT JOIN (
    SELECT
        ID AS OFFER_STATUS_ID1,
        TITLE AS SETTLEMENT_OFFER_STATUS_NAME1
    FROM DPP_DATA.READER.SETTLEMENT_OFFER_STATUS
) AS SETTLEMENT_OFFER_STATUS1 ON OFFER_STATUS_ID1 = OFFER_STATUS
CROSS JOIN LATERAL FLATTEN(
    INPUT => PARSE_JSON(SETTLEMENT_OFFERS.JSON):fees
) AS FLATTENED_FEES
ORDER BY OFFER_ID, PROCESS_DATE ASC;