create or replace view DATA_ALPS.DATA_VAULT.VW_TRANSACTIONS_2(
	ACTIVE,
	ID,
	LINKED_TO,
	DEBT_ID,
	OFFER_ID,
	CONTACT_ID,
	CREATED_AT,
	CREATED_BY_USER,
	INOUT,
	DRAFT_DATE,
	PROCESS_DATE,
	CLEARED_DATE,
	RETURNED_DATE,
	TRANSACTION_TYPE_NAME,
	TRANSACTION_SUBTYPE_NAME,
	TRANS_ID,
	MEMO,
	AMOUNT,
	NET_AMOUNT,
	TRANSACTIONS_STATUS_NAME,
	PAYEE_NAME
) as 

WITH

CTE_USERS AS (
    SELECT
        UID AS USER_ID1,
        CONCAT_WS(' ', FIRSTNAME, LASTNAME) AS USER_FULL_NAME
    FROM DPP_DATA.READER.USERS
),

CTE_LINK_TO_PF AS (
    SELECT DISTINCT
        ID AS TRANS_ID1,
        DEBT_ID,
        OFFER_ID
    FROM DPP_DATA.READER.TRANSACTIONS
    LEFT JOIN(
        SELECT
            ID AS OFFER_ID,
            DEBT_ID
        FROM DPP_DATA.READER.SETTLEMENT_OFFERS
    ) AS SETTLEMENT_OFFERS1 ON OFFER_ID = LINKED_TO
    WHERE TRANS_TYPE IN ('S')
),

CTE_LINK_TO_SETTLEMENTS AS (
    SELECT
        ID AS OFFER_ID,
        DEBT_ID
    FROM DPP_DATA.READER.SETTLEMENT_OFFERS
),

CTE_LINKED_TRANSACTIONS AS (
    SELECT DISTINCT
        ID AS TRANS_ID,
        COALESCE(CLTP.DEBT_ID, CLTS.DEBT_ID) AS DEBT_ID,
        COALESCE(CLTP.OFFER_ID, CLTS.OFFER_ID) AS OFFER_ID
    FROM DPP_DATA.READER.TRANSACTIONS
    LEFT JOIN CTE_LINK_TO_PF AS CLTP ON CLTP.TRANS_ID1 = LINKED_TO
    LEFT JOIN CTE_LINK_TO_SETTLEMENTS AS CLTS ON CLTS.OFFER_ID = LINKED_TO
),

CTE_TRANSACTION_TYPE AS (
    SELECT
        TRANS_TYPE AS TRANSACTION_TYPE_ID1,
        TITLE AS TRANSACTION_TYPE_NAME,
        INOUT
    FROM DPP_DATA.READER.TRANSACTION_TYPES
),

CTE_TRANSACTION_SUBTYPES AS (
    SELECT
        ID AS TRANSACTION_SUBTYPE_ID1,
        TITLE AS TRANSACTION_SUBTYPE_NAME
    FROM DPP_DATA.READER.TRANSACTION_SUBTYPES
),

CTE_TRANSACTIONS_STATUS AS (
    SELECT
        ID AS TRANSACTION_STATUS_ID1,
        NAME AS TRANSACTIONS_STATUS_NAME
    FROM DPP_DATA.READER.TRANSACTION_STATUSES
),

CTE_PAYEES AS (
    SELECT
        ID AS TRANSACTION_PAYEE_ID1,
        PAYEE_NAME
    FROM DPP_DATA.READER.PAYEES
),

CTE_TRANSACTIONS AS (
    SELECT
        *,
        IFF(INOUT = 'O', -AMOUNT, AMOUNT) AS NET_AMOUNT
    FROM DPP_DATA.READER.TRANSACTIONS
    LEFT JOIN CTE_USERS AS CU ON CU.USER_ID1 = CREATED_BY
    LEFT JOIN CTE_LINKED_TRANSACTIONS AS CLT ON CLT.TRANS_ID = ID
    LEFT JOIN CTE_TRANSACTION_TYPE AS CTT ON CTT.TRANSACTION_TYPE_ID1 = TRANS_TYPE
    LEFT JOIN CTE_TRANSACTION_SUBTYPES AS CTS ON CTS.TRANSACTION_SUBTYPE_ID1 = SUB_TYPE
    LEFT JOIN CTE_TRANSACTIONS_STATUS AS CTES ON CTES.TRANSACTION_STATUS_ID1 = STATUS
    LEFT JOIN CTE_PAYEES AS CTP ON CTP.TRANSACTION_PAYEE_ID1 = PAID_TO
    ORDER BY CONTACT_ID, PROCESS_DATE ASC
)

SELECT
    IFF(ACTIVE = 1, TRUE, FALSE) AS ACTIVE,
    ID,
    LINKED_TO,
    DEBT_ID,
    OFFER_ID,
    CONTACT_ID,
    CREATED_AT,
    USER_FULL_NAME AS CREATED_BY_USER,
    INOUT,
    DRAFT_DATE,
    PROCESS_DATE,
    CLEARED_DATE,
    RETURNED_DATE,
    TRANSACTION_TYPE_NAME,
    TRANSACTION_SUBTYPE_NAME,
    TRANS_ID,
    MEMO,
    AMOUNT,
    NET_AMOUNT,
    TRANSACTIONS_STATUS_NAME,
    PAYEE_NAME
FROM CTE_TRANSACTIONS;